AWSTemplateFormatVersion: '2010-09-09'
Description: 'PDF Processing Pipeline - DynamoDB Table'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  BillingMode:
    Type: String
    Default: PAY_PER_REQUEST

Resources:
  ProcessingStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '\-processing-status-\'
      BillingMode: !Ref BillingMode
      AttributeDefinitions:
        - AttributeName: file_key
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: file_key
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Processing Status Tracking

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref ProcessingStatusTable

  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt ProcessingStatusTable.Arn

  TableStreamArn:
    Description: ARN of the DynamoDB table stream
    Value: !GetAtt ProcessingStatusTable.StreamArn
