AWSTemplateFormatVersion: '2010-09-09'
Description: 'PDF Processing Pipeline - S3 Buckets'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  S3BucketPrefix:
    Type: String

Resources:
  # Input Bucket for PDF files
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3BucketPrefix}-input-${Environment}-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: PDF Input Storage

  # Output Bucket for processed text files
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3BucketPrefix}-output-${Environment}-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: GLACIER
                TransitionInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Processed Text Storage

  # Bucket policy for output bucket
  OutputBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OutputBucket
      PolicyDocument:
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${OutputBucket}/*'
              - !Ref OutputBucket
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

Outputs:
  InputBucketName:
    Description: Name of the input S3 bucket
    Value: !Ref InputBucket

  InputBucketArn:
    Description: ARN of the input S3 bucket
    Value: !GetAtt InputBucket.Arn

  OutputBucketName:
    Description: Name of the output S3 bucket
    Value: !Ref OutputBucket

  OutputBucketArn:
    Description: ARN of the output S3 bucket
    Value: !GetAtt OutputBucket.Arn
