AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  ProcessingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'pdf-processing-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: file_key
          AttributeType: S
      KeySchema:
        - AttributeName: file_key
          KeyType: HASH

Outputs:
  ProcessingTable:
    Value: !Ref ProcessingTable
    Export:
      Name: !Sub '${AWS::StackName}-ProcessingTable'