AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Default: dev
  DeployLayers:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']

Conditions:
  ShouldDeployLayers: !Equals [!Ref DeployLayers, 'true']

Resources:
  LayersBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pdf-layers-${Environment}-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  PDFProcessingLayer:
    Type: AWS::Lambda::LayerVersion
    Condition: ShouldDeployLayers
    Properties:
      LayerName: !Sub 'pdf-processing-layer-${Environment}'
      Description: 'PDF processing libraries: PyPDF2, pdfplumber'
      Content:
        S3Bucket: !Ref LayersBucket
        S3Key: 'pdf-layer.zip'
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11

  ImageProcessingLayer:
    Type: AWS::Lambda::LayerVersion
    Condition: ShouldDeployLayers
    Properties:
      LayerName: !Sub 'image-processing-layer-${Environment}'
      Description: 'Image OCR libraries: Pillow, pytesseract'
      Content:
        S3Bucket: !Ref LayersBucket
        S3Key: 'image-layer.zip'
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11

Outputs:
  LayersBucket:
    Value: !Ref LayersBucket
    Export:
      Name: !Sub '${AWS::StackName}-LayersBucket'
  PDFProcessingLayer:
    Condition: ShouldDeployLayers
    Value: !Ref PDFProcessingLayer
    Export:
      Name: !Sub '${AWS::StackName}-PDFProcessingLayer'
  ImageProcessingLayer:
    Condition: ShouldDeployLayers
    Value: !Ref ImageProcessingLayer
    Export:
      Name: !Sub '${AWS::StackName}-ImageProcessingLayer'