AWSTemplateFormatVersion: '2010-09-09'
Description: 'PDF Processing Pipeline - Main Stack'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

  ProjectName:
    Type: String
    Default: pdf-processing-pipeline
    Description: Name of the project

  S3BucketPrefix:
    Type: String
    Default: pdf-proc
    Description: Prefix for S3 bucket names (will be suffixed with account ID and region)

  TemplateS3Bucket:
    Type: String
    Description: S3 bucket containing nested CloudFormation templates

  TemplateS3KeyPrefix:
    Type: String
    Default: templates
    Description: S3 key prefix for nested templates

Mappings:
  EnvironmentMap:
    dev:
      DynamoDBBillingMode: PAY_PER_REQUEST
      LambdaMemorySize: 256
      SQSVisibilityTimeout: 360
    staging:
      DynamoDBBillingMode: PAY_PER_REQUEST
      LambdaMemorySize: 512
      SQSVisibilityTimeout: 360
    prod:
      DynamoDBBillingMode: PAY_PER_REQUEST
      LambdaMemorySize: 512
      SQSVisibilityTimeout: 360

Resources:
  # S3 Buckets Stack
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${TemplateS3KeyPrefix}/nested-stacks/s3.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        S3BucketPrefix: !Ref S3BucketPrefix
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # DynamoDB Stack
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${TemplateS3KeyPrefix}/nested-stacks/dynamodb.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        BillingMode: !FindInMap [EnvironmentMap, !Ref Environment, DynamoDBBillingMode]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  InputBucketName:
    Description: Name of the input S3 bucket
    Value: !GetAtt S3Stack.Outputs.InputBucketName
    Export:
      Name: !Sub 'pdf-pipeline-${Environment}-InputBucket'

  OutputBucketName:
    Description: Name of the output S3 bucket
    Value: !GetAtt S3Stack.Outputs.OutputBucketName
    Export:
      Name: !Sub 'pdf-pipeline-${Environment}-OutputBucket'

  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !GetAtt DynamoDBStack.Outputs.TableName
    Export:
      Name: !Sub 'pdf-pipeline-${Environment}-DynamoDBTable'
