AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step 1 - Single S3 Bucket Only'

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pdf-input-${Environment}-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Value: !Ref InputBucket
  BucketArn:
    Value: !GetAtt InputBucket.Arn